### ISSUE TITLE
Not able to see properly the settings page 

### ISSUE THREAD

**Issue by gcuofano** [awslabs/amazon-polly-wordpress-plugin#15]
This is the message I get in the settings page
![screen shot 2018-07-24 at 23 46 28](https://user-images.githubusercontent.com/26247261/43168019-ff50e064-8f9b-11e8-9014-7d6ec3b0cbea.png)

**Comment by tstachlewski** [comment]
Hi,
The reason will be one of those:
1) Your browser save other credentials that you actually provide.
2) Credentials are connected with AWS Account which is not activated. Could you log in into AWS - and open Polly service and see if there is no error notification saying that account is still not activated?

Let me know what have you found out.

Cheers,
Tomasz

**Comment by gcuofano** [comment]
Hi Tomasz, thanks for your help! I inserted the credentials manually and still don't see the proper settings. I also logged into AWS and I don't see any error. Not sure what I'm doing wrong.

**Comment by tstachlewski** [comment]
Hi,
So when you log into AWS, you then open Polly service, and you didn't any message saying that the account is not activate etc. - but instead of this you saw some kind of form where you were able to provide text and see how Polly is working - yes? Please make sure this is the case, it will help to solve the problem. If yes. then, assuming the account is active, could you try to log into your wordpress site from other webbrowser, maybe in cognito mode - and provide your credentials again? 

Cheers,

**Comment by tstachlewski** [comment]
Closing.
