### ISSUE TITLE
An option to add a custom intro/outro to each audio file

### ISSUE THREAD

**Issue by Caparico** [awslabs/amazon-polly-wordpress-plugin#6]
Since I cannot see this in the plugin options - I'd like to suggest adding the ability to upload a short intro/outro and have it automatically be added to each audio file generated by Amazon Polly.
That way, it will help content creators to easily create content that resembles a podcast, in the sense that they'll be able to present the creator and brand themselves and their site.

Thanks

**Comment by tstachlewski** [comment]
Hi Caparico!
In fact it's possible to do it now. There are two ways:
1) One is to use "AUDIO ONLY" functionality (added in 1.0.3) . So that you could add text to each post, which will be converted to audio, but won't be shown on the page itself.
2) The second possibility is to use filter which we have added in 1.0.5, which is called amazon_polly_content (I've added information about it to readme file). This allows users to modify the content which will be generated as they like, for example by adding some standard text to all mp3 :)

Cheers,
Tomasz

**Comment by kylewhenderson** [comment]
Hi Tomasz, I'm trying to use the filter amazon_polly_content to create the audio from a custom field instead of the content, but can't seem to be able to use the $post global to get the post id. Something like below, but just can't get it to work. Do you have any thoughts or suggestions?

`function get_narrator_text_callback() {
	global $post;
    $narration_text = get_field('narration_text', $post->ID);
	return $narration_text;
}
add_filter( 'amazon_polly_content', 'get_narrator_text_callback');`
